plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.linweiyun.minegenshin'
version = '1.0.0'

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

repositories { mavenCentral() }

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.commonmark:commonmark:0.24.0'
    implementation 'org.commonmark:commonmark-ext-gfm-tables:0.24.0'
}

bootJar { archiveFileName = 'minegenshin-web.jar' }

tasks.named('test') { useJUnitPlatform() }
